cloudogu/makefiles

- build/make/package-debian.mk
> Create control folder before executing PREPARE_PACKAGE target

- Makefile
- build/make/CHANGELOG.md
- build/make/clean.mk
- build/make/package-debian.mk
- build/make/variables.mk
- Remove cleaning DEBIAN_BUILD_DIR from default clean target (resolves #25 )
- Add ADDITIONAL_CLEAN target to define more clean steps (resolves #26 )
> Improve clean target

- CHANGELOG.md
- build/make/deploy-debian.mk
- Debian package (un)deployment for focal (Ubuntu 20.04); #56
- Debian package (un)deployment for xenial (Ubuntu 16.04); #56
Resolves #56
> Add focal debian package deployment

- CHANGELOG.md
- build/make/release.sh
Use main as production releases branch if existent
Resolves #60
> Main branch release

- CHANGELOG.md
- build/make/k8s.mk
> #80 Add `binary-yq` target to download and use yq on the fly

- CHANGELOG.md
- build/make/test-integration.mk
- build/make/variables.mk
> #87 Add fix for integration-tests

- CHANGELOG.md
- build/make/k8s-dogu.mk
> Use downloaded binary yq in k8s-dogu.mk #89

- CHANGELOG.md
- build/make/k8s-dogu.mk
- build/make/k8s.mk
> Use namespace environment variable

- CHANGELOG.md
- Makefile
- build/make/mockery.yaml
- build/make/mocks.mk
> #107 target for mocks

- CHANGELOG.md
- build/make/version-sha.mk
> #117 Add script to generate sha256sum

- CHANGELOG.md
- build/make/k8s-dogu.mk
- build/make/k8s.mk
> #119 add existing helm targets from k8s-component-operator to repo

- CHANGELOG.md
- build/make/k8s-controller.mk
- build/make/k8s-dogu.tpl
- build/make/k8s.mk
> Copy the whole helm chart.

- CHANGELOG.md
- build/make/k8s-helm-temp-chart.yaml
> #133 Added missing template-file k8s-helm-temp-chart.yaml

- CHANGELOG.md
- build/make/k8s-controller.mk
> #135 update controller-gen to v0.13.0

- CHANGELOG.md
- build/make/k8s.mk
> #137 Package generated Chart-Dependencies in Helm-Chart

- CHANGELOG.md
- build/make/k8s.mk
Use `yq` from `bin` instead of the host machine.
Resolves #139
> #139 Fix pipeline errors.

- CHANGELOG.md
- build/make/k8s-component.mk
- build/make/k8s-helm-dependency.tpl
> #147 remove Dummy-Chart-Dependencies from Helm-Chart-Generation

- CHANGELOG.md
- build/make/k8s-component.mk
- build/make/k8s-controller.mk
- build/make/k8s.mk
> Set bash as default shell in k8s.mk

- CHANGELOG.md
- README.md
- build/make/k8s-component.mk
- build/make/k8s-controller.mk
- build/make/k8s-crd.mk
> #152 add make targets for generating and packaging CRD helm-charts

- CHANGELOG.md
- Makefile
- build/make/coder-lib.sh
- build/make/coder.mk
- build/make/k8s-component.mk
- build/make/k8s-component.tpl
- build/make/k8s.mk
> Make the `image-import` for k8s components and controllers configurable

- CHANGELOG.md
- Makefile
- build/make/k8s-component.mk
> #159 #160 Update Helm binary to 3.13, add more helm support

- CHANGELOG.md
- build/make/coder-lib.sh
> #162 check if coder secrets dir exists

- CHANGELOG.md
- build/make/release.mk
- build/make/release_cve.sh
> #164 make cve severity configurable

- CHANGELOG.md
- build/make/release_cve.sh
> #166 Use --no-cache in dogu-cve-release and make fixed CVE-list unique

- CHANGELOG.md
- build/make/k8s-component.mk
- build/make/k8s-controller.mk
- build/make/k8s-crd.mk
- build/make/k8s-dogu.mk
- build/make/k8s.mk
- build/make/mocks.mk
> #160 remove monolitic YAML resource support in favor of Helm templates

- CHANGELOG.md
- build/make/k8s-dogu.mk
> 174 remove duplicate version tag

- CHANGELOG.md
- README.md
- build/make/k8s-component.mk
- build/make/k8s-crd.mk
- build/make/k8s-dogu.mk
- build/make/k8s.mk
> #188 support remote runtimes and container-registries for k8s-make-targets

- CHANGELOG.md
- build/make/bats.mk
- build/make/bats/Dockerfile
> #190 update BATS to 1.11, add docker default ARG values

- CHANGELOG.md
- build/make/k8s-dogu.tpl
> Use dogu v2 api

- CHANGELOG.md
- build/make/release.mk
- use "make dogu-release DRY_RUN=true"
> [#209] pass DRY_RUN Parameter to "make dogu-release"

- CHANGELOG.md
- build/make/release.mk
> Image-release

- CHANGELOG.md
- build/make/build.mk
- build/make/k8s.mk
- build/make/static-analysis.mk
> #238 upgrade controller gen to v0.19.0 and go to 1.25

- CHANGELOG.md
- build/make/static-analysis.mk
> #240 Upgrade Lint version to 2.5.0
