Makefile, README.md, build/make/package-debian.mk, build/make/variables.mk
This changes the "debian" make target to not compile
any binary any more but only compress all files in
the deb folder into a .deb file.
The "package" make target will continue to compile
a binary before generating the .deb file.
This also has an impact on the "upload-package" target, which now also does not compile a binary any more.
Resolves #8
=> Make debian target only pack files without compiling

README.md, build/make/package-debian.mk
During the upgrade of a Debian package configuration files may change
on both sides: the host, and the new package. This will lead to a
conflict which the package management tool is able to resolve in very
simple terms (f. i. no merge is possible).
The way how the `cesapp` Debian package is built does not support this
way of conflict solution. Instead, the package's configuration files
overwrite any changes made to the config files on the host.
This can lead to CES instances which will not be able to cope with non-
matching configurations up to that the CES instance will cease to
function properly.
This commit changes the build process by adding file that lists the
configuration files so that:
1. the Debian package management can recognize a set of given files as
config files
2. the …
=> #12 Adhere to debian conflict mgmt for config files; add new lint target

Makefile
This change ensures that the TMP_DIR exists before the `update-makefiles` target is executed.
Resolves #11
=> Make sure the TMP_DIR exists before updating makefiles

build/make/package-debian.mk
Copy files to data folder with the access permissions
they already have without using the install command.
Also make sure the data folder is created before.
Resolves #18
=> Copy files to data folder with existing permissions

build/make/package-debian.mk
$(CONFFILES_FILE_TMP) is removed after usage so it is not filled with duplicates if the deb package is built again.
Resolves #20
=> Remove temporary conffiles file after usage

build/make/variables.mk
Changing the owner and group to 0, because `cloudogu` and `1000` do not make much sense. This fixes the lintian errors described in #23 
Resolves #23
=> Change owner and group to 0 when tarring

build/CHANGELOG.md, build/make/build.mk, build/make/dependencies-gomod.mk, build/make/static-analysis.mk, build/make/test-common.mk, build/make/test-integration.mk, build/make/test-unit.mk, build/make/variables.mk
`Go mod` comes with some necessary environment variables. These may be vital for
running a whole project on `go mod` like tests, utility installation, building,
to just name a few. As not every project may want to set variables (not to speak
of using go modules) setting environment variables are purely optional.
Go module is activated by setting `GO_ENVIRONMENT=GO111MODULE=on` before
including `variables.mk`
Furthermore this commit fixes a weird unit-test behaviour when the go-junit tool
is older than the tests.
=> #31 support `go mod` dependency resolution and customizable go commands

CHANGELOG.md, Makefile, build/make/build.mk
Make Go environment variables configurable via the main Makefile
Resolves #41
=> Go environment variable configuration

CHANGELOG.md, build/make/test-common.mk
=> Call go mod vendor after retrieving the `go-junit-report` dependency

CHANGELOG.md, build/make/bower.mk, build/make/variables.mk, build/make/yarn.mk
- Make the nodejs version adjustable via NODE_VERSION variable
- `node:8` remains as the default
- Resolves #64
=> Make the nodejs version adjustable

CHANGELOG.md, build/make/release_functions.sh
Use the [:alpha:] characters class instead of the a-Z range, because the range does not work with grep v3.7 any more.
Resolves #66
=> Use alphabetic characters class instead of a-Z range

build/make/release.sh, build/make/release_functions.sh
During the release process it might be necessary to modify version within files
that are not tracked by the makefiles (files like Dockerfile, pom.xml, Makefile,
and so on). It also makes sense to not extend these files in all eternity but
rather create true extensibility.
This commit adds this extensibility by having a fixed file in the project's
workspace: `release_args.sh`. This file may define shell functions which are
optionally called (if found) by `release_functions.sh`.
=> #68 Extend release shell scripts with extension points

build/make/k8s-dogu.mk
Using `GNU Make 4.2.1` and sed `4.7` breaks when using a `#` as delimiter in sed commands
Resolves #82
=> #82 Change sed delimiter from `#` to `|`

CHANGELOG.md, build/make/k8s-controller.mk, build/make/k8s-dogu.mk, build/make/k8s.mk
K8s releases were temporary generated either in `target` for controllers or in `target/make/k8s` for other.
Use consistent `target/make/k8s` folder with `<artifact_id>_<version>.yaml` as file name.
Resolves #86
=> Use same temporary k8s yaml resource file name

CHANGELOG.md, build/make/static-analysis.mk
- Upgrade golanci-linter to 1.49.0
- Upgrade used go version to 1.18
- Use exit code 0 on linting issues to prevent pipeline failure
- Delete vet target because vet is used in golangci-lint
Resolves #94
=> Update target static-analysis.mk #94

CHANGELOG.md, build/make/k8s.mk
This var is no longer needed but was mandatory to set it because it was used in the check var target.
Resolves #103
=> Remove the env var K8S_CLUSTER_ROOT

CHANGELOG.md, build/make/k8s.mk
Remove helmify and just copy the release resource in the helm chart because the helmify generation does not fit with our name prefixes and does not recognize some properties like `publishNotReadyAddresses` from the service spec.
Resolves #127
=> Remove helmify

CHANGELOG.md, build/make/k8s.mk
Using go1.22 leads to a panic because of nil pointer dereference. Version 0.14.0 fixed this problem
Resolve #178
=> Upgrade controller_gen_version to v0.14.0

CHANGELOG.md, build/make/vulnerability-scan.mk
This PR adds the feature to scan vulnerabilities in go repositories using govulncheck. In contrast to trivy, govulncheck checks whether the vulnerability is used in the code.
For more information check: 
https://go.dev/doc/tutorial/govulncheck
=> Add make target to scan for vulnerabilities

CHANGELOG.md, build/make/k8s.mk
The docker-build target depends on the BINARY_YQ target, because inside it the IMAGE variable is used. In the moment this variable is used, it is evaluated and the evaluation depends on the yq binary.
=> Add missing yq dependency on docker-build target

CHANGELOG.md, build/make/test-common.mk, build/make/test-unit.mk
Use json as output format for "go test -json ..."
The result file needs to be referenced in dependent projects as:
`sonar.go.tests.reportPaths=target/unit-tests/report.json`
=> change unittest-report generation from xml to json

CHANGELOG.md, build/make/k8s.mk
Some variables were declared with double-quotes like CES_REGISTRY_HOST="registry.cloudogu.com". The string value of the variable is then "registry.cloudogu.com" (including the double-quotes) which lead to errors in sed , yq and other tools
closes #214
=> #214 removed double-quotes from variable-declaration in k8s.mk

CHANGELOG.md, build/make/k8s-component.mk, build/make/k8s-crd.mk, build/make/k8s.mk
in development-stage add a timestamp as buildnumber to helm-chart-version to force helm to use the updated chart
closes #233
=> allow "component-apply" and "crd-component-apply" in development-stage on remote-environments

CHANGELOG.md, build/make/bats.mk, build/make/bats/Dockerfile, build/make/bats/customBatsEntrypoint.sh
This PR
- resolves #235 
- updates BATS from 1.11 to 1.12
- chowns the report files back to non-root
=> Bugfix/235 re-add local report file
